server:
  port: 8082

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: resume-analyzer-service
  kafka:
    bootstrap-servers: kafka:9092
    topic:
      name: notification.events
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8080
ws:
  endpoint:
    open-ai-api: "https://api.openai.com/v1/chat/completions"
jwt:
  secret: PHkr3e4RdIuAjrtQ1WAoSYWmFlQVABVSPzZsjl1q8jw=  # Must match the one in auth-service
openai:
  api-key: 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

