server:
  port: 8080

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

jwt:
  secret: YOUR_GENERATED_SECRET  # Generate using the JwtSecretGenerator in the common-library config folder
  expiration: 3600000  # 1 hour in milliseconds
