server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  kafka:
    bootstrap-servers: kafka:9092
    topic:
      name: notification.events
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8080
jwt:
  secret: { JWT_SECRET }  # Must match the one in auth-service
openai:
  api-key: { OPEN_AI_KEY }

